# Generated by Django 3.2.9 on 2021-11-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('postdata', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('business', 'Business'), ('life', 'Life'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='samplemodel',
            name='title',
        ),
    ]
